@startuml Diagrama de estados
!pragma layout smetana
state shuffleCards
shuffleCards : barajar_repartir
state State2 <<choice>>
state State3

[*] --> shuffleCards
shuffleCards -> State2 : accion1
State2 --> [*] : [condicion]
State2 --> State3 : [falso]
State3 --> [*] : accion2