@startuml Class Diagram
!pragma layout smetana
title Klondike  - Class Diagram

class Klondike
class Player
class Tableau
class Foundation
class Pile
class Stock
class Stack
class Goal
class Card {
  +Int color
  +Int number
  +boolean turned
}
class Action
class Shuffle
class Move
class Deal


Klondike *-down-> "1" Player
Klondike *-down-> "4" Foundation
Klondike *-down-> "1" Tableau
Klondike *-down-> "1" Stock
Klondike *-down-> "1" Waste

Foundation *-down-> "0..52" Card

Tableau *-down-> "7" Pile
Pile *-down-> "0..*" Card

Stock *-down-> "0..24" Card
Waste *-down-> "0..3" Card

Player o-down-> "1" Goal
Goal .down.> "1" Foundation

Goal .down.> "1" Action
Action <|-down- "1" Shuffle
Action <|-down- "*" Move
Action <|-down- "*" Deal
Action .down.> "*" Card
Action .down.> "*" Pile

Stack <|-down- "1" Foundation
Stack <|-down- "1" Pile

@enduml
