@startuml ObjectDiagram
!pragma layout smetana
title Klondike  - Objects Diagram

object ":Klondike" as Klondike
object ":Waste" as Waste
object ":Stock" as Stock
object ":Pile" as Pile3
object ":Pile" as Pile4
object ":Pile" as Pile5
object ":Pile" as Pile6
object ":Pile" as Pile7
object ":Pile" as Pile8
object ":Pile" as Pile9
object ":Foundation" as Foundation

object ":Card" as Card1 {
    color: random
    number: random
    turned: false
}

object ":Card" as Card21 {
    color: black
    number: 7
    turned: true
}

object ":Card" as Card22 {
    color: black
    number: 4
    turned: true
}

object ":Card" as Card23 {
    color: red
    number: Q
    turned: true
}

object ":Card" as Card3 {
    color: red
    number: K
    turned: true
}

object ":Card" as Card4 {
    color: red
    number: 9
    turned: true
}

object ":Card" as Card41 {
    color: random
    number: random
    turned: false
}

object ":Card" as Card5 {
    color: black
    number: 3
    turned: true
}

object ":Card" as Card51 {
    color: random
    number: random
    turned: false
}

object ":Card" as Card6 {
    color: red
    number: J
    turned: true
}

object ":Card" as Card61 {
    color: random
    number: random
    turned: false
}

object ":Card" as Card7 {
    color: black
    number: 9
    turned: true
}

object ":Card" as Card71 {
    color: random
    number: random
    turned: false
}

object ":Card" as Card8 {
    color: red
    number: 7
    turned: true
}

object ":Card" as Card81 {
    color: random
    number: random
    turned: false
}

object ":Card" as Card9 {
    color: red
    number: A
    turned: true
}

object ":Card" as Card91 {
    color: random
    number: random
    turned: false
}

Klondike *-right-> Foundation
Klondike *-left-> Stock
Klondike *-left-> Waste
note  "Is Empty" as FNote
Foundation .right FNote
Klondike *--> Pile3
Klondike *--> Pile4
Klondike *--> Pile5
Klondike *--> Pile6
Klondike *--> Pile7
Klondike *--> Pile8
Klondike *--> Pile9

Stock -left- Card1
note "Stock have 21\n cards turned down." as C1N
Card1 . C1N

Waste -left- Card21
Waste -- Card22
Waste -- Card23

Pile3 -down-  Card3

Pile4 --  Card4
Pile4 --  Card41
note "1" as C4N
Card1 . C4N

Pile5 --  Card5
Pile5 --  Card51
note "2" as C5N
Card51 . C5N

Pile6 --  Card6
Pile6 --  Card61
note "3" as C6N
Card61 . C6N

Pile7 --  Card7
Pile7 --  Card71
note "4" as C7N
Card71 . C7N

Pile8 --  Card8
Pile8 --  Card81
note "5" as C8N
Card81 . C8N

Pile9 --  Card9
Pile9 --  Card91
note "6" as C9N
Card91 . C9N

note "Pile1 have 1 card turned up.\nPile2 have 1 card turned up and 1 card turned down\nPile3 have 1 card turned up and 2 cards turned down\nPile4 have 1 card turned up and 3 cards turned down\nPile5 have 1 card turned up and 4 cards turned down\nPile6 have 1 card turned up and 5 cards turned down\nPile7 have 1 card turned up and 6 cards turned down\n." as PNote
Pile3 ... PNote
Pile4 ... PNote
Pile5 ... PNote
Pile6 ... PNote
Pile7 ... PNote
Pile8 ... PNote
Pile9 ... PNote

@enduml
