@startuml StateDiagram
title Klondike  - State Diagram
!pragma layout smetana

state CardInDeck
state CardInPile
state CardInStock
state CardInFoundation
state GameFinal <<choice>>
state RestartGame
state GameWin

[*] --> CardInDeck
CardInDeck --> CardInDeck: Shuflle
CardInDeck --> CardInPile: DealToPile
CardInDeck --> CardInStock: DealToStock

CardInPile --> CardInPile: PileToPileMove
CardInPile --> CardInFoundation: PileToFoundationMove
CardInFoundation --> CardInPile: FoundationToPileMove

CardInStock --> CardInWaste: DealToWaste
CardInWaste --> CardInStock: WasteToStockMove
CardInWaste --> CardInPile: WasteToPileMove
CardInWaste --> CardInFoundation: WasteToFoundationMove

CardInFoundation --> GameFinal
GameFinal --> TryAnother: [NoMoreMoves]
GameFinal --> GameWin: [IsFoundationFull]

TryAnother --> [*]
GameWin --> [*]

@enduml
