@startuml StateDiagram
!pragma layout smetana
title Klondike  - State Diagram

!pragma layout smetana
state CardInDeck
state CardInPile
state CardInStock
state CardInFoundation

[*] --> CardInDeck
CardInDeck --> CardInDeck: shuffleCards
CardInDeck --> CardInPile: deal28Cards
CardInDeck --> CardInStock: deal24Cards

CardInPile --> CardInPile: moveCard
CardInPile --> CardInFoundation: moveCard
CardInFoundation --> CardInPile: moveCard

CardInStock --> CardInWaste: deal3Cards
CardInWaste --> CardInStock: moveAllCards
CardInWaste --> CardInPile: moveCard
CardInWaste --> CardInFoundation: moveCard

CardInFoundation --> [*]: [isFoundationFull]
CardInWaste --> [*]: [areMoreMoves]

@enduml
