@startuml ActivitiesDiagram
title Klondike  - Activities Diagram
!pragma layout smetana

start

:Shuffle;
:DealToPile Pile1;

while (areSeven Pile on Klondike)  is (No)
  :move toNext Pile;
  :DealToPile;
  while (areIn Pile oneCardMoreThanLast Pile)  is (No)
    :DealToPile;
  endwhile (Yes)
endwhile (Yes)

:turnUp firstCard on each Pile;
:DealToStock;
:DealToWaste;

while ()
  switch (isSelectedCard)
    case ()
      :PileToPileMove;
    case ()
      :PileToFoundationMove;
    case ()
      :FoundationToPileMove;
    case ()
      :WasteToFondationMove;
    case ()
      :WasteToPileMove;
    case ()
      :WasteToStockMove;
  endswitch

  if (isFoundationFull) then (yes)
    :WinGame;
    break;
  else (no)
    if (haveMoreMoves) then (no)
      :TryAnother;
      break;
    else (yes)
    endif
  endif
endwhile

stop

@enduml
