@startuml UseCaseMoveCard 
!pragma layout smetana
state Deck
state Deal
state Stock
state Waste
state Foundation
state Pile
state Restar
state Win
state Out <<choice>>
state move <<choice>>
state if <<choice>>
state if2 <<choice>>
state if3 <<choice>>
state if4 <<choice>>

[*] --> Deck
Deck --> Deck: shuffleCards
Deck --> Deal
Deal --> Stock
Stock --> Waste
Waste --> if2: [ifCardMovableToFoundation]
if2 --> Foundation 
Waste --> if: [ifCardMovableToPile]
if --> Pile
Pile --> if3: [ifPileMovableToAnotherPile]
if3 --> Pile

Pile --> if4: [ifCardMovableToFoundation]
if4 --> Foundation
Foundation --> Out

Out --> Win
Out --> Restar

Win --> [*]
Restar --> [*]
@enduml