@startuml StateDiagram
!pragma layout smetana
title Klondike  - DealPile - Status Diagram

state State1
state State2
state State3  <<choice>>
state State4
state State6
state State5 <<choice>>
state State8

[*] --> State1: ShuffleCards
State1 --> State2: DealCardToFirstPile
State2 --> State3: [areSevenPile]
State3 --> State4: MoveNextPile
State4 --> State6: DealCardPile
State6 --> State5: [isPileComplete]
State5 --> State6: DealAnotherCard
State5 --> State2: ContinueAnotherPile
State3 --> State8: TurnUpFirstCards

@enduml
