@startuml UCFoundationtoPileMove
!pragma layout smetana
title Klondike - FoundationtoPileMove  - Use Case Diagram

state IN_GAME
state CARD_IN_FOUNDATION
state if <<choice>>
state CARD_IN_PILE

[*] --> IN_GAME
IN_GAME --> CARD_IN_FOUNDATION: Player take card from Foundation
CARD_IN_FOUNDATION --> if: [< CardNumber AND DiferentColor]
if --> CARD_IN_PILE: FoundationToPileMove
if --> CARD_IN_FOUNDATION: TryAnotherMovement
CARD_IN_PILE--> [*]

@enduml
