@startuml UCRestartGame
title Klondike  - RestartGame - User Case Diagram
!pragma layout smetana

state OUT_GAME
state CARDS_SHUFFLE
state CARDS_IN_DECK
state START_GAME

[*] --> OUT_GAME
OUT_GAME --> CARDS_SHUFFLE: User request Restart
CARDS_SHUFFLE --> START_GAME: System deal cards
START_GAME --> [*]: User sees restarted game

@enduml
