@startuml UseCaseFoundationtoPileMove
!pragma layout smetana
title Klondike  - Case of Use Diagram - FoundationtoPileMove
state IN_GAME

state if <<choice>>


state CardsInStock

[*] --> IN_GAME
IN_GAME --> if: [StockIsEmpty]
if --> CardsInStock: MoveCardsToStock

if --> [*]

CardsInStock--> [*]

@enduml