@startuml StateDiagramGameStates(ContextDiagram)
!pragma layout smetana
state INITIAL 
state IN_GAME 
state OUT_GAME
state EXIT
state if_finished <<choice>>
state if_resumed <<choice>>

[*] --> INITIAL: Shuffle
INITIAL --> IN_GAME: DealPile
IN_GAME --> if_finished: DealStock
IN_GAME --> if_finished: MoveCard
IN_GAME --> if_finished: MovePile
if_finished --> IN_GAME
if_finished --> OUT_GAME: [finished]
OUT_GAME --> if_resumed: ResetDeck
if_resumed --> IN_GAME: [continued]
if_resumed --> EXIT
EXIT --> [*]
@enduml