@startuml ActorsDiagram
title Klondike  - UseCase Diagram
left to right direction
!pragma layout smetana

actor Player

usecase Login
usecase StartGame
usecase DealToWaste
usecase PileToPileMove
usecase PileToFoundationMove
usecase FoundationToPileMove
usecase WasteToPileMove
usecase WasteToFondationMove
usecase WasteToStockMove
usecase Undo
usecase Redo
usecase RestartGame

Player --> Login
Player --> StartGame
Player --> DealToWaste
Player --> PileToPileMove
Player --> PileToFoundationMove
Player -->  FoundationToPileMove
Player -->  WasteToPileMove
Player -->  WasteToFondationMove
Player -->  WasteToStockMove
Player -->  Undo
Player -->  Redo
Player -->  RestartGame

@enduml
