@startuml UCWasteToPileMove
!pragma layout smetana
title Klondike  - UseCaseWasteToPileMove - User Case Diagram

state IN_GAME
state CARD_IN_WASTE
state if <<choice>>
state CARD_IN_PILE

[*] --> IN_GAME
IN_GAME --> CARD_IN_WASTE: Player take card from Waste
CARD_IN_WASTE --> if: [< CardNumber AND DiferentColor \n OR CardNumer is K]
if --> CARD_IN_PILE: WasteToPileMove
if --> CARD_IN_WASTE: TryAnotherMovement
CARD_IN_PILE --> [*]

@enduml
