@startuml DetailActivityDiagram
title Klondike  - Restart - Case of Use Diagram 
!pragma layout smetana

state RESTART
state SHUFFLE
state CARD_TO__STOCK
state DEAL

[*] --> RESTART : User request Restart
RESTART --> SHUFFLE: System shuffle cards
SHUFFLE --> DEAL: System deal cards
DEAL--> CARD_TO__STOCK: System move leftover cards to stock
CARD_TO__STOCK  -->[*]: User sees restarted game
@enduml