@startuml UCWasteToStockMove
!pragma layout smetana
title Klondike  - WasteToStockMove - User Case Diagram

state IN_GAME
state CARDS_IN_WASTE
state if <<choice>>
state CARDS_IN_STOCK

[*] --> IN_GAME
IN_GAME --> CARDS_IN_WASTE: PlayerRequireMoveWasteToStock
CARDS_IN_WASTE --> if: [isStockEmpty]
if --> CARDS_IN_STOCK: WasteToStockMove
if --> [*]: TryAnotherMovement
CARDS_IN_STOCK --> [*]

@enduml
