@startuml UCUndo
title Klondike  - Undo - User Case Diagram
!pragma layout smetana

state UNDO_REQUEST
state CARD_IN_PAST_POSITION

[*] --> UNDO_REQUEST : User request undo
UNDO_REQUEST --> CARD_IN_PAST_POSITION: System check saved past position
CARD_IN_PAST_POSITION --> [*]: User sees undo card

@enduml
