@startuml UseCaseContextDiagram
!pragma layout smetana
title Klondike  - Context Diagram - User Case Relationship

state INITIAL
state GAME_READY
state IN_GAME
state OUT_GAME
state EXIT
state if_finished <<choice>>
state if_resumed <<choice>>

note "PileToPileMove\nPileToFoundationMove\nWasteToFoundationMove\nWasteToPileMove\nFondationToPileMove\nWaisteToStockMove\nUndo\nRedo" as PNote

if_finished ---> PNote
[*] --> INITIAL: Login
INITIAL --> GAME_READY: StartGame
GAME_READY--> IN_GAME: DealToWaste
IN_GAME --> if_finished: MoveCard
if_finished --> IN_GAME
if_finished --> OUT_GAME: [finished]
OUT_GAME --> if_resumed: RestartGame
if_resumed --> INITIAL: [continued]
if_resumed --> EXIT
EXIT --> [*]

@enduml
