@startuml UseCaseWasteToPileMove
!pragma layout smetana
title Klondike  - Case of Use Diagram - UseCaseWasteToPileMove


state IN_GAME
state CARD_SELECTED
state if <<choice>>
state if2 <<choice>>

state CardToPile

[*] --> IN_GAME
IN_GAME --> CARD_SELECTED: Player take card from Waste
CARD_SELECTED --> if: [is"K"AndSomePileIsEmpty]
if --> if2:[isPreviousNumberAndDiferentColorInAnotherPile]
if --> CardToPile: MoveCardToAnotherPile
if2 --> CardToPile: MoveCardToAnotherPile
if2 --> [*]

CardToPile--> [*]

@enduml