@startuml UCResetDeck
!pragma layout smetana
title Klondike  - ResetDeck - Use Case Diagram

state OUT_GAME
state IN_WASTE
state IN_GAME
state RESTART_GAME

[*] --> OUT_GAME
OUT_GAME --> IN_WASTE: See waste is empty
IN_WASTE --> IN_GAME: Past the waste to the Stock
IN_WASTE --> RESTART_GAME: No more movemnets
IN_GAME --> [*]
RESTART_GAME --> [*]

@enduml
