@startuml UseCaseWasteToFoundationMove
!pragma layout smetana
title Klondike  - Case of Use Diagram - WasteToFoundationMove


state IN_GAME
state CARD_SELECTED
state if <<choice>>
state if2 <<choice>>

state CardToFoundation


[*] --> IN_GAME
IN_GAME --> CARD_SELECTED: Player take card from Waste
CARD_SELECTED --> if: [isCardAsAndFoundationEmpty]
if --> if2:[isNextNumberAndSameColorThatCardInFoundation]
if --> CardToFoundation: MoveCardToFoundation
if2 --> CardToFoundation: MoveCardToEmptyFoundation
if2 --> [*]


CardToFoundation--> [*]

@enduml