@startuml ArquitecturaMVC
!pragma layout smetana
title Paquetes MVC
top to bottom direction
' left to right direction

package Views {
    class DeckView
    class StockView
    class PilaView
    class CimientoView
}

package Controllers {
    class LoginController
    class DealToWasteController
    class PileToPileMoveController
    class PileToFoundationMoveController
    class UndoController
    class FoundationToPileMoveController
    class WasteToPileMoveController
    class WasteToFondationMoveController
    class WasteToStockMoveController
    class RedoController
    class RestartGameController
} 
package Models {
    class StackModel
    class CardModel
    class PlayerModel
    class WasteModel
    class FoundationModel
    class PileModel
    class StockModel
    StackModel <|-down- WasteModel
    StackModel <|-down- FoundationModel
    StackModel <|-down- PileModel
    StackModel <|-down- StockModel
}

@enduml 