@startuml ResetDeckContextDiagram
!pragma layout smetana
title Klondike  - ResetDeck - Context Diagram
left to right direction

actor Player
rectangle DeckView
rectangle ResetDeckController
rectangle Stock

Player --> DeckView: ResetDeck
DeckView --> ResetDeckController: ResetDeck
DeckView --> Stock: setNewCards()

@enduml
