@startuml ContextDiagram
!pragma layout smetana
title Klondike  - MoveCard - Context Diagram
left to right direction

actor Player
rectangle PileView
rectangle MoveCardController
rectangle Deck
rectangle StockView
rectangle Foundation
rectangle Pile

Player --> PileView: moveCard
PileView --> MoveCardController: moveCard
Player --> StockView: moveCard
StockView --> MoveCardController: moveCard
StockView ..> Deck: getNewCard()
MoveCardController ..> Foundation: moveCard
MoveCardController ..> Pile: moveCard

@enduml
